POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "One Piece",
  "important": true,
  "userId":"657f87ef0aa18ab1ec0f6128"
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "asheshs",
    "name": "Ashesh",
    "password": "badmin"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}